version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz_app
    ports:
      - "5432:5432"